Fix loading albumArt from Chromium MPRIS
elementary/wingpanel-indicator-sound pull request #280
Opened 2024-10-10 05:13 UTC by EndarValuk

Added new handle for Chromium browser based MPRIS metadata in a PlayerRow.

Before:
![Снимок экрана от 2024-10-04 13 36 27](https://github.com/user-attachments/assets/ca9013c8-f181-473d-9406-93e5ea4c487d)

After:
![Снимок экрана от 2024-10-10 10 13 01](https://github.com/user-attachments/assets/4793cf90-d0b9-4bbc-8db8-9b1500755a5d)

2024-10-10 17:37 UTC, danirabbit requested changes
Historically we have avoided adding application specific workarounds. Can this be reproduced with other flatpak apps as well? Can this be solved in way that isn't specifically hardcoding the Chrome RDNN?

For example at a minimum maybe can we check for the existing of the file in `/tmp` and if it isn't there, then we can check if it exists in `.flatpak` / application_id? I think we should be able to get the app ID from MPRIS

2024-10-11 05:32 UTC, EndarValuk commented
@danirabbit 

> Historically we have avoided adding application specific workarounds. Can this be reproduced with other flatpak apps as well? Can this be solved in way that isn't specifically hardcoding the Chrome RDNN?

Checked, its not a flatpak-specific "feature" of chromium. Its a "chromium" way.
Same behaviour persists even when using "deb-based" chromium distribution.
I will take look on it, for which apps its an applicable case.

> For example at a minimum maybe can we check for the existing of the file in `/tmp` and if it isn't there, then we can check if it exists in `.flatpak` / application_id? I think we should be able to get the app ID from MPRIS

I will take look on it, to implement a cleaner way.

> Probably should also use GLib.Path to build paths https://valadoc.org/glib-2.0/GLib.Path.build_path.html

I will update code according to that note

2024-10-15 11:03 UTC, EndarValuk commented
@danirabbit 
> I think we should be able to get the app ID from MPRIS
atleast, we got very strange behavior, dbus sending us something like that:
`org.mpris.MediaPlayer2.chromium.instance33959`
but we got an `com.google.Chrome` app name actually.

And if i'm right, current implementation doesnt allow us to get an actual app_info from stripped ifaces.
It will require refactoring a bit.

2024-10-15 18:26 UTC, danirabbit commented
Hm yeah this seems like it's just a bug upstream in Chromium and will need to be addressed there. This happens in both Chrome and Chromium so just hardcoding Chrome's app ID here doesn't fix it.

Another thing I can think of, it's kind of brute force, but you could iterate over every folder in `/run/user/1000/.flatpak` and check if the file exists in any of them. Not super clean, but it should work

2024-10-16 05:08 UTC, EndarValuk commented
> Another thing I can think of, it's kind of brute force, but you could iterate over every folder in `user_runtime_directory` / `.flatpak` and check if the file exists in any of them. Not super clean, but it should work

Added little bit more elegant solution with a regex

2024-10-17 19:04 UTC, danirabbit requested changes
That's definitely a lot smarter than iterating over every folder, nice job! Just gotta make sure to stick to code style conventions re variable naming, spaces, etc. See also linter output: https://github.com/elementary/wingpanel-indicator-sound/actions/runs/11359271917/job/31695048276?pr=280

https://docs.elementary.io/develop/writing-apps/code-style

2024-10-21 09:38 UTC, EndarValuk commented
@danirabbit code updated, but dont know what to do with lint erroring Regex literal.

2024-10-23 15:55 UTC, danirabbit commented
Hey sorry for taking a couple days to respond. We usually prefer printf syntax over string literals. See https://docs.elementary.io/develop/writing-apps/code-style#string-formatting

2024-10-23 17:11 UTC, EndarValuk commented
> Hey sorry for taking a couple days to respond. We usually prefer printf syntax over string literals. See https://docs.elementary.io/develop/writing-apps/code-style#string-formatting

I'm new in vala lang development, but never encountered printf syntax over regexp literals.

Anyway I've updated PR code. No more errors.
Is it now ok, on ur perception, to be merged?

2024-10-23 17:21 UTC, danirabbit approved these changes
This looks good to me. Nice fix!

2024-10-23 17:21 UTC, merged